#!/usr/bin/env python3

import logging
import sys
from signal import signal, SIGTERM

from energymonitor.devices.rpict import RPICT
from energymonitor.helpers.constants import VERSION
from energymonitor.services.datalogger import DataLogger
from energymonitor.services.interface import Interface

logging.basicConfig(stream=sys.stdout, level=logging.INFO, format='%(name)s - %(levelname)s: %(message)s')

if __name__ == "__main__":
    rpict = RPICT()
    rpict.start()

    interface = Interface()
    datalogger = DataLogger()

    def shutdown(signum, stack):
        interface.stop()
        sys.exit()
    signal(SIGTERM, shutdown)

    logging.getLogger(f'energy-monitor {VERSION} started!')
